# config/logstash.conf
input {
  tcp {
    port => 5000
    codec => json
  }
}

filter {
  mutate {
    add_tag => ["elk-stack"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    user => "elastic"
    password => "${ELASTIC_PASSWORD}"
    index => "logstash-%{+YYYY.MM.dd}"
    ssl_enabled => false
  }
}